openapi: 3.0.0
info:
  title: Shiny Barnacle API
  description: API documentation for shiny-barnacle
  version: 1.0.0
servers:
  - url: http://localhost:8002

components:
  schemas:
    Speaker:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the speaker.
        name:
          type: string
          description: The name of the speaker.
        email:
          type: string
          format: email
          description: The email address of the speaker.
        phoneNumber:
          type: string
          description: The phone number of the speaker.
      required:
        - name
        - email

    Sponsor:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the sponsor.
        name:
          type: string
          description: The name of the sponsor.
        email:
          type: string
          format: email
          description: The email address of the sponsor.
        phoneNumber:
          type: string
          description: The phone number of the sponsor.
        address:
          type: string
          description: The address of the sponsor.
        contribution:
          type: number
          description: The contribution amount of the sponsor.
      required:
        - name
        - email
        - phoneNumber
        - address
        - contribution

    Agenda:
      type: object
      properties:
        name:
          type: string
          description: The name of the agenda.
        description:
          type: string
          description: The description of the agenda.
        startTime:
          type: string
          format: date-time
          description: The start time of the agenda.
        endTime:
          type: string
          format: date-time
          description: The end time of the agenda.

    Session:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the session.
        speakerId:
          type: string
          description: The ID of the speaker associated with the session.
        name:
          type: string
          description: The name of the session.
        description:
          type: string
          description: The description of the session.
        agendaId:
          type: string
          description: The ID of the agenda associated with the session.
      required:
        - speakerId
        - name
        - description
        - agendaId

    Event:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the event.
        name:
          type: string
          description: The name of the event.
        description:
          type: string
          description: The description of the event.
        duration:
          type: number
          description: The duration of the event.
        status:
          type: string
          description: The status of the event.
          enum:
            - draft
            - published
            - cancelled
        sponsors:
          type: array
          description: The sponsors associated with the event.
          items:
            type: string
            format: ObjectId
        sessions:
          type: array
          description: The sessions associated with the event.
          items:
            type: string
            format: ObjectId
        organizer:
          type: string
          description: The organizer of the event.
          format: ObjectId
      required:
        - name
        - description
        - duration
        - status
        - organizer

paths:
  /api/shiny-barnacle/speaker/get-all:
    get:
      summary: Get all speakers
      description: Retrieve a list of all speakers.
      tags:
        - Speaker
      responses:
        "200":
          description: A list of speakers successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Speaker"
        "404":
          description: No speakers found

  /api/shiny-barnacle/speaker/create:
    post:
      summary: Create a new speaker
      description: Add a new speaker to the system.
      tags:
        - Speaker
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Speaker"
      responses:
        "201":
          description: Speaker created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Speaker"
        "400":
          description: Invalid request body or missing required fields

  /api/shiny-barnacle/speaker/update/{id}:
    put:
      summary: Update a speaker
      description: Update an existing speaker's details.
      tags:
        - Speaker
      parameters:
        - in: path
          name: id
          description: ID of the speaker to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Speaker"
      responses:
        "200":
          description: Speaker updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Speaker"
        "400":
          description: Invalid request or speaker ID
        "404":
          description: Speaker not found

  /api/shiny-barnacle/speaker/delete/{id}:
    delete:
      summary: Delete a speaker
      description: Delete an existing speaker from the system.
      tags:
        - Speaker
      parameters:
        - in: path
          name: id
          description: ID of the speaker to delete
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Speaker deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Speaker"
        "400":
          description: Invalid speaker ID
        "404":
          description: Speaker not found

  /api/shiny-barnacle/sponsor/get-all:
    get:
      summary: Get all sponsors
      description: Retrieve a list of all sponsors.
      tags:
        - Sponsor
      responses:
        "200":
          description: A list of sponsors successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sponsor"
        "404":
          description: No sponsors found

  /api/shiny-barnacle/sponsor/create:
    post:
      summary: Create a new sponsor
      description: Add a new sponsor to the system.
      tags:
        - Sponsor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sponsor"
      responses:
        "201":
          description: Sponsor created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sponsor"
        "400":
          description: Invalid request body or missing required fields

  /api/shiny-barnacle/sponsor/update/{id}:
    put:
      summary: Update a sponsor
      description: Update an existing sponsor's details.
      tags:
        - Sponsor
      parameters:
        - in: path
          name: id
          description: ID of the sponsor to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sponsor"
      responses:
        "200":
          description: Sponsor updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sponsor"
        "400":
          description: Invalid request or sponsor ID
        "404":
          description: Sponsor not found

  /api/shiny-barnacle/sponsor/delete/{id}:
    delete:
      summary: Delete a sponsor
      description: Delete an existing sponsor from the system.
      tags:
        - Sponsor
      parameters:
        - in: path
          name: id
          description: ID of the sponsor to delete
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sponsor deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sponsor"
        "400":
          description: Invalid sponsor ID
        "404":
          description: Sponsor not found

  /api/shiny-barnacle/agenda/get-all:
    get:
      summary: Get all agendas
      description: Retrieve a list of all agendas.
      tags:
        - Agenda
      responses:
        "200":
          description: A list of all agendas
  /api/shiny-barnacle/agenda/create:
    post:
      summary: Create a new agenda
      description: Add a new agenda to the system.
      tags:
        - Agenda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Agenda"
      responses:
        "200":
          description: Agenda created successfully
        "400":
          description: Bad request
  /api/shiny-barnacle/agenda/update/{id}:
    put:
      summary: Update an agenda
      description: Update an existing agenda's details.
      tags:
        - Agenda
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the agenda to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Agenda"
      responses:
        "200":
          description: Agenda updated successfully
        "400":
          description: Bad request
  /api/shiny-barnacle/agenda/delete/{id}:
    delete:
      summary: Delete an agenda
      description: Delete an existing agenda from the system.
      tags:
        - Agenda
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the agenda to delete
      responses:
        "200":
          description: Agenda deleted successfully
        "400":
          description: Bad request

  /api/shiny-barnacle/session/create:
    post:
      summary: Create a new session
      description: Add a new session to the system.
      tags:
        - Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Session" # Assuming you have a schema defined for sessions
      responses:
        "200":
          description: Session created successfully
        "400":
          description: Bad request

  /api/shiny-barnacle/session/get-all:
    get:
      summary: Get all sessions
      description: Retrieve a list of all sessions.
      tags:
        - Session
      responses:
        "200":
          description: A list of all sessions

  /api/shiny-barnacle/session/update/{id}:
    put:
      summary: Update a session
      description: Update an existing session's details.
      tags:
        - Session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the session to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Session" # Assuming you have a schema defined for sessions
      responses:
        "200":
          description: Session updated successfully
        "400":
          description: Bad request
        "404":
          description: Session not found

  /api/shiny-barnacle/session/delete/{id}:
    delete:
      summary: Delete a session
      description: Delete an existing session from the system.
      tags:
        - Session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the session to delete
      responses:
        "200":
          description: Session deleted successfully
        "400":
          description: Bad request
        "404":
          description: Session not found

  /api/shiny-barnacle/event/create:
    post:
      summary: Create a new event
      description: Create a new event in the system.
      tags:
        - Event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "200":
          description: Event created successfully
        "401":
          description: Unauthorized - JWT token is missing or invalid

  /api/shiny-barnacle/event/get-organizer-events:
    get:
      summary: Get events created by organizer
      description: Retrieve a list of events created by the organizer.
      tags:
        - Event
      responses:
        "200":
          description: A list of events created by the organizer
        "401":
          description: Unauthorized - JWT token is missing or invalid

  /api/shiny-barnacle/event/get/{id}:
    get:
      summary: Get event by ID
      description: Retrieve event details by its ID.
      tags:
        - Event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event details retrieved successfully
        "404":
          description: Event not found

  /api/shiny-barnacle/event/update/{id}:
    put:
      summary: Update event by ID
      description: Update an existing event's details by its ID.
      tags:
        - Event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "200":
          description: Event updated successfully
        "401":
          description: Unauthorized - JWT token is missing or invalid
        "404":
          description: Event not found

  /api/shiny-barnacle/event/delete/{id}:
    delete:
      summary: Delete event by ID
      description: Delete an existing event from the system by its ID.
      tags:
        - Event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event deleted successfully
        "401":
          description: Unauthorized - JWT token is missing or invalid
        "404":
          description: Event not found
